#!/bin/sh
# file: docbook/manuals

# ====================================================================
# 
# --------------------------------------------------------------------

if [ ! -d /usr/local/bin/cmassoc  ]; then
	echo "You do not have Motley Tools installed. Sorry!"
	exit 1
fi

# ====================================================================
#
# --------------------------------------------------------------------

export MANWIDTH=100
INDEX=toolkit.html
STYLE=toolkit.css

# ====================================================================
#
# --------------------------------------------------------------------

# unset LANG

# ====================================================================
#
# --------------------------------------------------------------------

cp ../pib/piboffset.* .
for file in ../gcc/cmassoc/*.1; do echo ${file}; man ${file} > $(basename ${file}); done
for file in ../gcpp/programs/*.1; do echo ${file}; man ${file} > $(basename ${file}); done
if [ -f ../scripts/*.sh ]; then
	for file in ../scripts/*.sh; do cp ${file} .; done
	fi
purge -vr ../t.c
import -r . '../*.h' '../*.c' 

# ====================================================================
#
# --------------------------------------------------------------------

catalog -s ${STYLE} -gdp ${INDEX} -c 4 *.1 > manual.txt
catalog -s ${STYLE} -gdp ${INDEX} -c 4 *.h > header.txt
catalog -s ${STYLE} -gdp ${INDEX} -c 4 *.c > source.txt
if [ -f *.sh ]; then
	catalog -s ${STYLE} -gdp ${INDEX} -c 4 *.sh > script.txt
else
	touch script.txt
	fi
cat part1.txt manual.txt part2.txt header.txt part3.txt source.txt part4.txt script.txt part5.txt > ${INDEX}
rm -f manual.txt header.txt source.txt script.txt batch.txt applet.txt 

