.TH phptidy 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
phptidy - format PHP source code

.SH SYNOPSIS
.BR phptidy
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.PP
.BR phptidy
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]

.SH DESCRIPTION

.PP
Format PHP source code without disturbing surrounding text or markup language.
Formatting is highly stylized and customized to suit the authors preferences.
If you do not like the format then do not use the program.

.PP
This program uses the \fBotidy\fR class to format language constructs.

.SH OPTIONS

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.
Usethis option when sending screen dumps to Intellon Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH ARGUMENTS

.TP
.BR file
The name of a PHP or HTML source file.
This file is replaced with the formatted output and a numbered backup file is created.
Attempts to format syntactically incorrect source files may result in unpredictable output or program errors.

.SH EXAMPLES
This example formats source file \fBabc.php\fR.
Backup file \fBabc.php.nnn\fR is automatically created in case recovery is required.

.PP
   # phptidy abc.php

.PP
The next example reads file \fBabc.php\fR from stdin and writes formatted output to \fBdef.php\fR on stdout.
This will prevent the input file from being overwritten.
Program output may now be piped into another application.

.PP
   # phptidy < abc.php > def.php

.PP
The next example reads file \fBabc.html\fR from stdin and formats embedded PHP source without disturbing surrounding text or markup.
Output is then piped into program \fBhtmltidy\fR to format the HTML source without disturbing embedded PHP source.
Of course, formatting could be done in the opposite order to obtain the same or similar results.

.PP
   # phptidy < abc.html | htmltidy > def.html

.SH SEE ALSO
.BR afm ( 7 ),
.BR cfm ( 7 ),
.BR ctidy ( 7 ),
.BR csstidy ( 7 ),
.BR dnstidy ( 7 ),
.BR htmltidy ( 7 ) 
.BR xmltidy ( 7 ) 

.SH AUTHORS
 Charles Maier <cmaier@cmassoc.net>

