.TH blank 1 "May 2013" "cmassoc-tools-1.9.0" "Motley Tools"

.SH NAME
blank - minimize blank lines in a file

.SH SYNOPSIS
.BR blank
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.PP
.BR blank
.RI [ options ]
.RI [< file ] 
.RI [> file ]

.SH DESCRIPTION
Reduce consecutive blank lines to a specified minimum in a text file.
This program can be used to shrink files after they are processed by programs that leave a large number of blank lines.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBn\fI count\fR
Reduce consecutive blank lines that exceed this number to this number.
Shorter consecutive runs are not affected.
A count of 0 eliminates blank lines.
The default count is 0.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a text file.
This file is replaced and a numbered backup is created.
Use program \fBrex\fR to recover a prior version.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR crlf ( 1 ), 
.BR lam ( 1 ), 
.BR rex ( 1 ), 
.BR space ( 1 ), 
.BR trim ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
