.TH catalog 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
catalog - catalog text files

.SH SYNOPSIS
.BR catalog
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.SH DESCRIPTION

.PP
Print a browseable catalog of text files.
The catalog consists of one HTML page for each file with the file forming the page body.
The HTML pages are linked so that they can be browsed, either forward or backward, using a web browser.
A multi-column index page can also be produced.
This program can be used to catalog large numbers of source code files, for example.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBc\fI columns\fR
The number of columns displayed in the index page.
The default number of columns is 5.

.TP
.RB - d
Delete text files after creating pages.
Use this option only if you can replace the text files.

.TP
.RB - g
Replace selected text with ISO glyphs.
Use this option when text files contain the characters '\fB<\fR', '\fB>\fR' or '\fB&\fR'.

.TP
.RB - i
Print an index page on stdout.
The page lists each cataloged file with a link to the corresponding page.

.TP
-\fBp\fI page\fR
The path to the index page.
This path is used as the href attribute for the HOME link on each page.
This path should match that used with option \fB-i\fR.
The default path is "index.html".

.TP
-\fBt\fI text\fR
The title of the catalog index page.
The title is used as the title attribute for the HOME link on each page.
It will appear as the tooltip when the mouse hovers over that link.
The default title is "Index Page".

.TP
-\fBs\fI file\fR
The path to the stylesheet that is referenced by all pages.
The default stylesheet is "stylesheet.css".

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a text file.
A new HTML file is created having this name with the additional file extension, "\fB.html\fR".
The page will be linked to other files specified on the same command line.
The original file is not modified.

.SH EXAMPLES
The following example creates an HTML page for each header and source file in the current folder.
Page names are the original file name plus the \fB.html\fR extension.
One can open any page and navigate to any other using PREV and NEXT links provided on each page.

.PP
   # catalog *.c *.h

.PP
The rext example does the same but also writes an HTML index page to stdout because option \fB-i\fR is specified.
The ouput is redirected to \fBindex.html\fR.
The index page contains links to each page created.
One can move to the index page from any other page using the HOME link provided on each page.

.PP
   # catalog *.c *.h -i > index.html 

.SH SEE ALSO
None

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

