.TH cdep 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
cdep - Display C Language file dependencies

.SH SYNOPSIS
.BR cdep 
.IR file 
.RI [ file ]
.RI [ ... ] 
.RI [> file ]

.SH DESCRIPTION
Search C language source files and print relationships defined by the pre-processor \fB#include\fR statements.
Relationsips are printed in alphabetical order by file.
Relationships have two forms: \fBneed\fR where one file needs another and \fBfeed\fR where one file feeds another.
These forms are merely the inverse of each other.

.SH OPTIONS

.TP
.RB - c
Consider only custom files.
Custom files are those enclosed in quotes.
This option excludes option \fB-s\fR.

.TP
.RB - f
Display an alphabetical list of files with files that they feed.
One file feeds another if it must be included by that file.
This display can be viewed as a "where used" list.
This option excludes option \fB-n\fR.

.TP
.RB - n
Display an alphabetical list of files with files that they need.
One file needs another if it must include that file.
This option excludes option \fB-f\fR.

.TP
.RB - s 
Consider only system files.
System files are those enclosed in angle brackets.
This option excludes option \fB-c\fR.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.

.SH ARGUMENTS

.TP
.IR file
The name of a C language file.
One or more files may appear on the command line.
Each file should be syntactically correct or errors can occur.

.SH EXAMPLES
The following example prints a list of system files used by program \fBabc.c\fR.
This list is essentially an inventory of required system files.

.PP
   # cdep abc.c

.PP
The rext example does the same as above but lists custom files, instead.
If all these files were stored in an archive file then the program should be complete.

.PP
   # cdep abc.c -c

.PP
The following example prints an analysis of custom files needed by program \fBabc.c\fR.
Files are listed in alphabetical order and each file is followed by an indented list of the files that it needs.

.PP
   # cdep abc.c -c -n

.SH SEE ALSO
.BR call ( 1 ),
.BR cblock ( 1 ),
.BR cbrief ( 1 ),
.BR cinc ( 1 ),
.BR cmerge ( 1 ),
.BR ctar ( 7)

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

