.TH defix 7 "December 2012" "plc-utils-2.1.3" "Qualcomm Atheros Powerline Toolkit"
.SH NAME
defix - extract argument prefix/suffix
.SH SYNOPSIS
.BR defix
.RI [ options ]
.IR string
.RI [ string ] 
.RI [ ... ]
.SH DESCRIPTION
.PP
.SH OPTIONS
Long options are not supported.
All options are single letters.
.TP
-\fBc\fI c\fR
Separator character.
.TP
.RB - i
Separator is optional.
.TP
.RB - m
Separator is mandatory.
.TP
.RB - o
Separator is optional.
.TP
.RB - p
Extract prefix.
.TP
.RB - s
Extract suffix.
.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.
.SH ARGUMENTS
.SH EXAMPLES
None.
.SH SEE ALSO
None.
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

