.TH delta 1 "May 2013" "cmassoc-tools-1.9.0" "Motley Tools"

.SH NAME
delta - print deltas between consecutive numbers

.SH SYNOPSIS
.BR delta
.RI [ options ]
.IR file 
.RI [ file ]
.RI [ ... ]
.RI [> file ]

.PP
.BR delta
.RI [ options ]
.RI [< file ]
.RI [> file ]

.SH DESCRIPTION
None.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a data file.
Data files consist of decimal integers separated by whitespace.
A hash ('#') or semicolon (';') causes remaining text on the line to be ignored.
This file is not modified.

.SH EXAMPLES
The following is an example data file, \fBtimer.txt\fR, containing the absolute time, in seconds since the epoch, when a series of events occured.
Three comment lines start the file and will be ignored.
One line contains several times.

.PP
   # ===============
   # seconds;
   # ---------------
   643708 
   643722 
   643723 643725 643726 
   643727 
   643728 
   643731 
   643732 
   643733

.PP
The following prints the difference between each value in \fBtimer.txt\fR.
This tells us how much time passed between each event.
It is now obvious that some time intervals are significantly longer than others.
Some analysis may be in order.

.PP
   # delta timer.txt 
   14
   1
   2
   1
   1
   1
   3
   1
   1

.PP
The rext example does the same but sorts the differences to groups similar values together.
This starts to illustrate the distribution of time intervals but not well enough..

.PP
   # delta timer.txt | sort
   1
   1
   1
   1
   1
   1
   2
   3
   14

.PP
The rext example does the same, again, but sorts then counts like differences.
We can see, from this small sample that 6 events took 1 second, one event took 2 seconds, one took 3 seconds and one took 14 seconds.
We now have enough information to produce a distribution chart or histogram.

.PP
   # delta timer.txt | sort | uniq -c
   6 1
   1 2
   1 3
   1 14

.SH SEE ALSO
.BR graph ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
