.TH enbrace 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
enbrace - enclose script symbols in braces

.SH SYNOPSIS
.BR enbrace
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.PP
.BR enbrace
.RI [ options ]
.RI [< file ]
.RI [> file ]

.SH DESCRIPTION
Search one or more text files for symbolic references that start with "\fB$\fR" and enclose them in paired braces, if they are not already enclosed.
For example, symbolic reference "\fB$PWD\fR" will become "\fB${PWD}\fR" on the first pass but will not change on subsequent passes.

.PP
The use of braces to enclose symbolic constants makes global search-and-replace operations easy and, in many cases, makes scripts easier to read.

.SH OPTIONS

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a text file.
This file is replaced and a numbered backup is created.
Use program \fBrex\fR to recover a prior version.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR afm ( 1 ),
.BR blank ( 1 ),
.BR cbrief ( 1 ),
.BR cedit ( 1 ),
.BR crlf ( 1 ),
.BR detab ( 1 ),
.BR enfix ( 1 ),
.BR entab ( 1 ),
.BR rex ( 1 )
.BR sbrief ( 1 ),
.BR space ( 1 ),
.BR trim ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

