.TH englyph 7 "GNU General Public License Version 2" "cmassoc-utils-1.8.1" "Motley Toolkit"
.SH NAME
englyph - (under construction)
.SH SYNOPSIS
.BR englyph
.RI [ options ]
.IR file 
.RI [ file ]
.RI [ ... ] 
.RI [> file ]
.PP
.BR englyph
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]
.SH DESCRIPTION
None.
.SH OPTIONS
.TP
.RB - q
.TP
.RB - v
.TP
.RB - ? ,-- help
Print program help summary on stdout. This option takes precedence over other options on the command line. 
.TP
.RB - ! ,-- version
Print program version information on stdout. This option takes precedence over other options on the command line. 
.SH ARGUMENTS
.TP
.IR file
.SH EXAMPLES
None.
.SH SEE ALSO
None.
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
