.TH ff 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
ff - find files

.SH SYNOPSIS
.BR ff
.RI [ options ]
.IR filespec
.RI [ filespec ]
[...]

.SH DESCRIPTION
Recursively searche a root folder for files that match wildcard filename specification and print the fullpath to each matching file on stdout.
Optionally, the file date and time may be printed or just the pathname or just the basename.

.PP
It may be used to locate missing files, produce text files containing filenames or to compare the date and time of files found in multiple folders.

.SH SEARCH SPECIFICATIONS
A search specification looks like a normal filename specification with a \fBpathname\fR and a \fBbasename\fR part.
Either part may be ommitted or abbreviated.
The basename part can be a filename or a \fBwildcard\fR pattern.
When more than one search specification appears on the command line then each search is performed in order.

.PP
A single search starts in the folder specified by the pathname component and iterates through files in that folder looking for regular files that match the filename or wildcard specified by the basename component.
Special files, such as devices, fifos and sockets are always ignored.
Symbolic links are ignored unless enabled.
Matching files are executed as shell scripts if they are executable and contain a valid script header.
The folder search resumes after script completion and ends when all the files in the folder have been inspected.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - B
Search binary folders \fB{,/usr}{/bin,/sbin}\fR and \fB/usr{/local}/bin\fR, in that order, for matching files.

.TP
-\fBE \fIvariable\fR
Search folders listed in the named environment variable, in left to right order, for matching files.

.TP
.RB - I
Search include folders \fB{/usr{,/local}}/include\fR, in that order, for matching files.

.TP
.RB - L
Search library folders \fB{/usr{,/local}}/lib\fR, in that order, for matching files.

.TP
.RB - P 
Search folders listed in the ${PATH} environment variable, in left to right order, for matching files.
This option is equivalent to "\fB-E PATH\fR".

.TP
.RB - S
Search system folders \fB{/bin,/etc,/lib,/sbin,/var}\fR, in that order, for matching files.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH FILES
None.

.SH SEE ALSO
.BR import ( 1 ),
.BR purge ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

