.TH filesize 1 "May 2013" "cmassoc-tools-1.9.0" "Motley Tools"

.SH NAME
filesize - print filesizes on stdout

.SH SYNOPSIS
.BR filesize
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.SH DESCRIPTION
Print the name and size of one or more files on stdout.
The filename and filesize are shown in fixed-column format followed by a scaled bar consisting of hash characters.
When multiple files are specified, the output forms a histogram showing the relative filesizes.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBd\fI digits\fR
The maximum number of digits used to display the file size in bytes.
The default is \fB8\fR digits.

.TP
-\fBw\fI width\fR
The maximum number of characters used to display the file name.
Longer names are truncated.
The default is \fB16\fR characters.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a file.
The file is not modified.
The file name is display along with the file size in bytes and a scaled horizontal bar.

.SH EXAMPLES
None.

.SH SEE ALSO
None.

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
