.TH hex2bin 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
hex2bin - hexadecimal to binary concatenate

.SH SYNOPSIS
.BR hex2bin
.RI [ options ]
.IR file
.RI [ file ]
[...]
.RI [> stdout ]

.PP
.BR hex2bin
.RI [< stdin ]
.RI [> stdout ]

.SH DESCRIPTION
Read one or more hexadecimal octet streams and output one binary stream.
Use program \fBbin2hex\fR to reverse the process.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBa\fI column\fR
Discard text occuring after this column.
The default column is UINT_MAX, defined in limits.h.

.TP
-\fBb\fI column\fR
Discard text occuring before this column.
The default column is 0.

.TP
.RB - q
Quiet mode.
This option has no effect at this time.

.TP
.RB - v
Verbose mode.
This option has no effect at this time.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file 
The name of a hexadecimal input file, possible created using program \fBbin2hex\fR.
Input files are not modified.
One output stream is written.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR bin2hex ( 1 ),
.BR dmp2hex ( 1 ),
.BR hexcmp ( 1 ),
.BR hexdmp ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

