.TH ifd 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"
.SH NAME
ifd - Interface Diagram Generator
.SH SYNOPSIS
.BR ifd
.RI [ options ]
.IR file 
.RI [ file ]
.RI [ ... ] 
.RI [> file ]
.PP
.BR ifd
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]
.SH DESCRIPTION
None.
.SH OPTIONS
.TP
.RB - a
Number transactions at the start instead of at both ends.
This results in fewer numbers and a less congested diagram.
.TP
.RB - l
Draw the first transaction \fBleft-to-right\fR.

This is the default direction.

.TP
.RB - r
Draw the first transaction \fBright-to-left\fR.
The default direction is \fBleft-to-right\fR.

.TP
-\fBn\fR step\fR
The starting step number.

Permitted values are \fB1\fR through \fB512\fR.
The default is \fB1\fR.
.TP
.RB - q
Quiet mode.
Suppress normal progress or status information on stdout.
.TP
.RB - v
Verbose mode.
Print additional progress or status information on stdout.
.TP
-\fBw\fI width\fR
Transaction width in columns.
The default is \fB40\fR columns.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.

.SH ARGUMENTS
.TP
.IR file
The name of an inteface definition file.
The file is read but not modified.
Interface definition files contain one or more text lines where each line represents a transaction.
Blank lines are ignored.
Interface definition files end in \fB.ifd\fR by convention.

.SH EXAMPLES
This is an example interface definition file, \fBtest.ifd\fR.
It consists of 9 lines that name 6 transactions.
Consecutive blank lines are output as one line and introduce a gap between otherwise adjacent transactions.
.PP
   Step1
       Step2
   Step3
   
   Step4
   
   
      Step5
   Step6
.PP
The following example reads file \fBtest.ifd\fR and prints the corresponding interface diagram on stdout.
Observe that the first transaction is \fBleft-to\right\fR and steps are labeled \fB1\fR through \fB12\fR.
You, as an author, must describe for each step so that readers understand the diagram.
.PP
   # ifd test.ifd

    [01] |------------------- Step1 ------------------->| [02]
    [04] |<------------------ Step2 --------------------| [03]
    [05] |------------------- Step3 ------------------->| [06]
         |                                              |     
    [08] |<------------------ Step4 --------------------| [07]
         |                                              |     
    [09] |------------------- Step5 ------------------->| [10]
    [12] |<------------------ Step6 --------------------| [11]

.PP
The next example reverses the direction of all transactions because option \fB-l\fR is present and numbering starts with step \fB3\fR because option \fB-n\fR is present.
.PP
   # ifd -l -n 3 test.ifd
    
     [04] |<------------------ Step1 --------------------| [03]
     [05] |------------------- Step2 ------------------->| [06]
     [08] |<------------------ Step3 --------------------| [07]
          |                                              |     
     [09] |------------------- Step4 ------------------->| [10]
          |                                              |     
     [12] |<------------------ Step5 --------------------| [11]
     [13] |------------------- Step6 ------------------->| [14]
    
.PP
The next example is identical to the first except that transactions ar only numbered at their start instead of at both ends because option \fB-a\fR is present.
We call this "alternate" numbering because it appears to alternate.
This minimizes the number of steps that must be documented.
.PP
   # ifd -a test.ifd
   
    [01] |------------------- Step1 ------------------->|     
         |<------------------ Step2 --------------------| [02]
    [03] |------------------- Step3 ------------------->|     
         |                                              |     
         |<------------------ Step4 --------------------| [04]
         |                                              |     
    [05] |------------------- Step5 ------------------->|     
         |<------------------ Step6 --------------------| [06]
   
.SH SEE ALSO
None.
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
