.TH l2p 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
l2p - list-to-pair conversion

.SH SYNOPSIS
.BR l2p
.RI [ options ]
.IR file
.IR file
.RI [ file ] 
.RI [ ... ]

.SH DESCRIPTION
Convert a labelled list to the equivalent series of label/value pairs where a list has the form "\fBlabel\fR: [\fBvalue\fR] [\fBvalue\fR] [...]".

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a text file containing one or more labelled lists.
The file is not modified by this program.

.SH EXAMPLES
Assume we have file \fBabc.txt\fR containing two labelled lists.
.PP
   label1: value1 value2 value3;
   label2: value3 value4 value5 value6;
.PP
This example reads file \fBabc.txt\fR and outputs the equivalent label/value pairs on stdout.
The output is suitable as input to other toolkit programs such as \fBorder\fR.
.PP
   # l2p abc.txt 
   label1:value1;
   label1:value2;
   label1:value3;
   label3:value3;
   label3:value4;
   label3:value5;
   label3:value6;
.PP
The next example pipes the output into program \fBorder\fR for further processing.
.PP
   # l2p abc.txt | order -t 
   label1
      value1
      value2
      value3
   label3
      value3
      value4
      value5
      value6

.SH SEE ALSO
.BR order (7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
