.TH localhost 1 "May 2013" "cmassoc-tools-1.9.0" "Motley Tools"

.SH NAME
localhost - manage host/domain name

.SH SYNOPSIS
.BR localhost
.RI [ options ]

.SH DESCRIPTION
Set the local host and/or domain name.
The fully qualified domain name, of \fBfdqn\fR, for any computer consists of the local hostname and the network domain name.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBd\fI domain\fR
The network domain name.
This string is written to file \fB/proc/sys/kernel/domainname\fR and will remain in effect until reboot.
On reboot, the hostname is read from parameter \fBkernel.domainname\fR in file \fB/etc/sysctl.conf\fR.

.TP
-\fBh\fI host\fR
The local hostname.
This string is written to file \fB/proc/sys/kernel/hostname\fR and will remain in effect until reboot.
On reboot, the domainname is read from parameter \fBkernel.domainname\fR in file \fB/etc/sysctl.conf\fR.

.TP
.RB - l
Create symlink \fB/etc/hostname\fR --> \fB/proc/sys/kernel/hostname\fR for use by dependent boot scripts.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH FILES    

.TP
/etc/hostname
Constains the hostname on many Linux distributions.
Option \fB-l\fR replaces this file with a symlink to /proc/sys/kernel/hostname which is used by the newer Linux kernels.

.TP
/proc/sys/kernel/hostname

.TP
/proc/sys/kernel/domainname

.SH EXAMPLES
The following example echos the fdqn on stdout.

.PP
   # localhost
   bugeye.mynetwork.net

.PP
The next example sets the host and domain name then echos the fdqn.

.PP
   # localhost -h booboo -d cartoon.com
   booboo.cartoon.com

.SH SEE ALSO
.BR syslog ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
