.TH matrix 7 "GNU General Public License Version 2" "cmassoc-utils-1.8.1" "Motley Toolkit"
.SH NAME
matrix - print parse matrix table
.SH SYNOPSIS
.BR matrix
.RI [ options ]
.IR file 
.RI [ file ]
.RI [ ... ] 
.RI [> stdout ]
.PP
.BR matrix
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]
.SH DESCRIPTION
Read a matrix definition file and print an HTML or DOCBOOK table on stdout. 
The output is suitable for use in the body of another HTML page or DOCBOOK section.
Use program \fBhtml\fR to embed HTML output from this program inside a template HTML page.
.PP
A matrix description file is similar to a comma-separated-value file but spaces are used to separate field and a semi-colon is used to separate tuples. The first line of the file defines table column headings. 
.SH OPTIONS
Long options are not supported. All options are single letters.
.TP
.RB - d
Print a table on stdout using DOCBOOK elements \fBtable\fR, \fBtitle\fR, \fBrow\fR and \fBentry\fR. 
The indent level can be varied using option \fB-i\fR.
.TP
-\fBe\fI string\fR
The string displayed inside empty table cells. 
The default is "\fB&nbsp;\fR" which displays as an empty cell.
.TP
.RB - h
Print table on stdout using HTML elements \fBtable\fR, \fBtr\fR and \fBtd\fR. 
The indent level can be varied using option \fB-i\fR. 
.TP
-\fBl\fI level\fR
The starting indent level. 
This option may be used to match the indent level of companion documents or document fragments.
Indents are implemented using horizontal tabs. 
Valid values are \fB0\fR through \fB16\fR. 
The default is \fB0\fR.
.TP
-\fBe\fI string\fR
The string displayed inside matching cells. 
This option is useful for short tables where the table header does not scroll off the screen.
The default is the column title.
.TP
.RB - q
Quiet mode. This option has no effect at this time.
.TP
.RB - s
Print a CSS stylesheet on stdout where class names match those in the HTML table. The stylesheet may be used to create new CSS stylesheets, included in existing CSS stylesheets or included in the HTML section.
.TP
.RB - v
Verbose mode. This option has no effect at this time.
.TP
.RB - ? ,-- help
Print program help summary on stdout. This option takes precedence over previous command line options. 
.TP
.RB - ! ,-- version
Print program version information on stdout. This option takes precedence over previous command line options.
.SH ARGUMENTS
.TP
\fIfile\fR
The name of a matrix definition file. A matrix definition file consists of one table column definition and many table row definitions. Table column and row definitions have the same format but distinguished by file position. The first is the table column definition while successive ones are row definitions.

A definition consists of one or more fields separated by white space. Definitions are separated from each other by one semi-colon. This means that a definition can straddle multiple lines and that a semi-colon must appear between the last field of a definition and the first field of the next definition. A semicolon need not appear after the last field of the last definition in a file and should be omitted to avoid creating an empty table row at the bottom of the output.
.SH EXAMPLES
An example matrix definition file, \fBmatrix.txt\fR, appears below. The first line is the table column definition. The remaining lines are table row definitions. There are 4 columns and 3 rows defined here. Names are separated by white space and each definition, except the last, is terminated by semicolon. Names may contain white space and puntuation when enclosed in quotes.
.PP
   Items List1 List2 List3;
   Item1 List2; 
   Item2 
     List1
     List3;
   Item3 List3
     List2
   
     List1
.PP
The following command reads file \fBmatrix.txt\fR (shown above) and writes an HTML table to stdout because HTML is the default output format.
.PP
   # matrix < matrix.txt > matrix.html
.PP
.PP
File \fBmatrix.html\fR will look something like this when viewed using a web browser. There will be additional formatting, of course, depending on browser and stylesheet settings.
.PP 
   Title
   Items List1 List2 List3
   Item1       Yes	  
   Item2 Yes         Yes
   Item3 Yes   Yes   Yes
.PP
File \fBmatrix.html\fR will look like this when opened using a standard text editor. See \fBhttp://www.w3.org/MarkUp/\fR for more information on HTML.
.PP
   <h1 class='matrix'>
   	Title
   	</h1>
   <table class='matrix'>
   	<tr class='matrix'>
   		<th class='matrix'>
   			Items
   			</th>
   		<th class='matrix'>
   			List1
   			</th>
   		<th class='matrix'>
   			List2
   			</th>
   		<th class='matrix'>
   			List3
   			</th>
   		</tr>
   	<tr class='matrix'>
   		<td class='matrix'>
   			Item1
   			</td>
   		<td class='empty'>
   			&nbsp;
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		<td class='empty'>
   			&nbsp;
   			</td>
   		</tr>
   	<tr class='matrix'>
   		<td class='matrix'>
   			Item2
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		<td class='empty'>
   			&nbsp;
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		</tr>
   	<tr class='matrix'>
   		<td class='matrix'>
   			Item3
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		<td class='match'>
   			Yes
   			</td>
   		</tr>
   	</table>
.PP
The next example pipes program output into program \fBhtml\fR to bracket the output with an HTML header and footer. 
Option \fB-h\fR is present to ensure output is in HTML format. 
Option \fB-l\fR is used to adjust the indent level to match that expected of program \fBhtml\fR. 
The result is saved in file \fBmatrix.html\fR. 
.PP
   # matrix -h -l2 matrix.txt | html > matrix.html
.PP
The next example reads file \fBmatrix.txt\fR and writes a DOCBOOK table to stdout because option \fB-d\fR is present.
.PP
   # matrix -d < matrix.txt > matrix.xml
.PP
File \fBmatrix.xml\fR will look like this when opened using a standard text editor. The element names are different thatn HTML but the basic principle is the same. See \fBhttp://www.docbook.org\fR for more information on DOCBOOK.
.PP
   <table>
   	<title>
   		Title
   		</title>
   	<tgroup>
   		<thead>
   			<row>
   				<entry>
   					Items
   					</entry>
   				<entry>
   					List1
   					</entry>
   				<entry>
   					List2
   					</entry>
   				<entry>
   					List3
   					</entry>
   				</row>
   			<thead>
   		<tbody>
   			<row>
   				<entry>
   					Item1
   					</entry>
   				<entry>
   					&nbsp;
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				<entry>
   					&nbsp;
   					</entry>
   				</row>
   			<row>
   				<entry>
   					Item2
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				<entry>
   					&nbsp;
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				</row>
   			<row>
   				<entry>
   					Item3
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				<entry>
   					Yes
   					</entry>
   				</row>
   			</tbody>
   		</tgroup>
   	</table>
.SH SEE ALSO
.BR html ( 7 ),
.BR offset ( 7 )
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
