.TH mp 1 "May 2013" "cmassoc-tools-1.9.0" "Motley Tools"

.SH NAME
mp - format man page header

.SH SYNOPSIS
.BR mp
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.PP
.BR mp
.RI [ options ]
.RI [< file ]
.RI [> file ]

.SH DESCRIPTION

.PP
Format Linux man pages to update header information, simplify text maintenance and correct common mistakes.

.PP
The man page filename and extension, taken from the command line, are used as the program name and folder number.
The title header, starting with "\fB.TH\fR", is updated using information from a user-defined configuration profile.
An empty line is inserted prior to each ".SH", ".TP" and ".PP" tag.

Sentences are each moved to a new line so that they can be easily edited or detected and replaced or removed by other programs.
Selected headers are detected and updated or preceded with one blank line.

.PP
This program can be used with program \fBnp\fR, for example, to perform global changes across multiple man pages.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - o
Print a template profile on stdout.
The template uses default program values.
Output can be directed to a file, edited and read back whenever the program is next executed.
This option takes precedence over normal formatting operations.

.TP
-\fBp\fI profile\fR
The profile name.
If this option is present then the program attempts to open and read the profile.
The program will report an error and terminated if the named profile file does not exist.
If this option is omitted the program attempts to read the default profile.
The program does not report an error when the default profile is missing.
The default profile is "\fB/etc/mp.ini\fR".

.TP
-\fBs\fI section\fR
The profile section name.
If this option is present the the program will search the named profile or default profile for the named section.
If this option is omitted the progam will search for the default section, instead.
The default section is named "\fBdefault\fR".

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of man page.
This file is replaced and a numbered backup is created.
Use program \fBrex\fR to recover a prior version.

.SH PROFILE
The default profile looks like:

.PP
   [default]
   project=Motley Tools
   package=motley-tools-1.5.9
   release=Feb 2004

.TP
.BR project
The project name appears at the top center of the page.
A reasonable value is the company or project name.
The default is "Motley Tools".

.TP
.BR package
The package name appears in the lower left of the page.
A reasonable value is the archive name with revision numbers.
The default is "cmassoc-tools-x.x.x".

.TP
.BR release
The release data appears at the bottom center of the page.
A reasonable value is the current month and year.
The default is the current month and year.

.SH EXAMPLES
The following example formats the ".TH" line of man page \fBmp.7\fR using default program values.

.PP
   # mp afm.7

.SH SEE ALSO
.BR afm ( 1 ),
.BR cfm ( 1 ),
.BR np ( 1 ),
.BR rex ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
