.TH mrg 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
mrg - merge-sort

.SH SYNOPSIS
.BR mrg
.RI [ options ]
.IR file
.RI [ file ]
.RI [ ... ]
.RI [> stdout]
.PP
.BR mrg
.RI [ options ]
.RI [< stdin ]
.RI [> stdout]

.SH DESCRIPTION
Merge ordered files into an ordered output stream.
The default order is ascending.
The merge process will terminate with an error message if any input file is not arranged in proper order

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RN - d
Indicates that input files are arranged in descending order.
If this option is omitted then ascending order is assumed.

.TP
.RB - l
Maximum line length in bytes.
The minimum is 1 and maximum is SHRT_MAX as defined in \fBlimits.h\fR.
The default is \fB1024\fR.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a ordered text file.
The file is not modified.
File order must match that specified (or implied) by the presence (or absence) of option \fB-d\fR.

.SH EXAMPLES
The following example merges sorted files \vBabc.txt\fR, \fBdef.txt\fR and \fBghi.txt\fR.
The order of files on the command line is not important but the order of file content is imporant.
Each file must be sorted in ascending order because option \fB-d\fR has been omitted.
.PP
   # mrg abc.txt def.txt ghi.txt
.PP
The next example does the same thing but all files must be arranged is descending order or an error will occur.
.PP
   # mrg -d abc.txt def.txt ghi.txt

.SH SEE ALSO
.BR srt ( 7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
