.TH paginate 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
paginate - paginate input

.SH SYNOPSIS
.BR paginate 
.RI [ options ]
.IR file
.RI [ file ]
.RI [ ... ]
.RI [> stdout ]

.PP
.BR paginate
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]

.SH DESCRIPTION
Read one or more input files and paginate on output.
Pagination means printing page headers and footers and wrapping long lines.
Page header include a title and date.
Page footers include the page numbers.
Page titles change with each input file but page numbers continue across input files.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBl\fI lines\fR
The page length in lines.
Input is segmented such that page headers and footers are inserted after this many lines are printed.
The page header and footer each occupy two lines and so the printed page must accomodate at least four additiona lines.
The default length is \fB60\fR lines.

.TP
-\fBw\fI columns\fR
The page width in columns.
Longer lines are wrapped.
The default width is \fB72\fR columns.

.TP
-\fBt\fI string\fR
The page title.
This title is used for stdin only.
If files are specified then the file basename is used instead.
The default title is "\fBuntitled\fR".

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS
None

.SH EXAMPLES
None.

.SH SEE ALSO
.BR vl ( 1 ),
.BR trim ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

