.TH preamble 7 "GNU General Public License Version 2" "cmassoc-utils-1.8.1" "Motley Toolkit"
.SH NAME
preamble - prepend/append text to files
.SH SYNOPSIS
.BR preamble
.RI [ options ]
.IR file
.RI [ file ] 
[...]
.PP
.BR preamble
.RI [ options ]
.RI [< stdin ] 
.RI [> stdout ]
.SH DESCRIPTION
Prepend and/or append text to files where the text is stored in a prefix and a suffix file.  Either the prefix or the suffix file or both may be omitted but omitting both files would be pointless.
.SH OPTIONS
Long options are not supported. All options are single letters.
.TP
-\fBp \fIfilename\fR
Name of the prefix file. This text is prepended to each file specified on the command line. No text is prepended when this option is omitted.
.TP
-\fBs \fIfilename\fR
Name of the suffix file. This text is appended to each file specified on the command line. iNo text is appended when this option is omitted.
.TP
.RB - ? ,-- help
Print program help summary on stdout. This option takes precedence over previous command line options. 
.TP
.RB - ! ,-- version
Print program version information on stdout. This option takes precedence over previous command line options.
.SH ARGUMENTS
.TP
.IR file
The name of a text file. This file is replaced and a numbered backup is created. Use program \fBrex\fR to recover a prior version.
.SH EXAMPLES
The following example prepends the contents of file \fBprefix.txt\fR and appends the contents of file \fBsuffix.txt\fR to all C language source and header files in the current folder.
.PP
   # preamble -p prefix.txt -s suffix.txt *.c *.h
.SH SEE ALSO
.BR enfix ( 7 ),
.BR rex ( 7 )
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

