.TH preamble 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
preamble - replace one C Language preamble with another

.SH SYNOPSIS
.BR preamble
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.PP
.BR preamble
.RI [ options ]
.RI [< file ]
.RI [> file ]

.SH DESCRIPTION

.PP
Replace one C Language preamble with another. 
The old preamble must match that found in an input file.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - c
Print filename only when the preamble is changed.

.TP
-\fBo\fI filename\fR
A file that contains the old preamble.
The old preamble is the first ANSI C Language comment block in this file.
White space that precedes, and text that follows, the preamble is ignored.
Any source file preamble matching this one will be replaced with the new preamble.

.TP
-\fBn\fI filename\fR
A file that contains the new preamble.
The new preamble is the first ANSI C Language comment block in this file.
White space that precedes, and text that follows, the preamble is ignored.
Any source file preamble matching the old preamble will be replaced with this one.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of an ANSI C Language source file.
This file is replaced and a numbered backup is created.
Use program \fBrex\fR to recover a prior version.

.SH EXAMPLES
The following example optionally replaces the preamble in all C Language source and header files in the current folder.
The old preamble is read from file \fBold.c\fR.
The new preamble is read from file \fBnew.c\fR.

.PP
   # preamble -o old.c -n new.c *.c *.h
.SH SEE ALSO
.BR cbrief ( 1 ),
.BR sandwich ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

