.TH quiet 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
quiet - enable/disable broadcast messages

.SH SYNOPSIS
.BR quiet
.RI [ options ]
.RB [ yes | no ]

.SH DESCRIPTION
Enable or disable the display of broadcast messages on your terminal.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.BR yes
Enable message display.

.TP
.BR no
Disable message display.

.SH EXAMPLES
None

.SH SEE ALSO
.BR shout ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

