.TH relate 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
Relate - Display dependency relationsips

.SH SYNOPSIS
.BR relate
.RI [ options ]
.RI [ file ]
.RI [ file ]
[...]
.PP
.BR relate
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]

.SH DESCRIPTION
Read one or more dependency files and organize the relationships.
Dependency files consists of name pairs, one pair per line.
Paired names are separated by a colon.
Pairs are terminated by a semicolon.

.SH OPTIONS

.TP
.RB - f
Display an alphabetical list of components with the components that they feed.

.TP
.RB - n
Display an alphabetical list of components with the components that they need.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.

.SH ARGUMENTS
None.

.SH EXAMPLES
None.

.SH SEE ALSO
None.

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
