.TH rex 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
rex - remove and replace file extension 

.SH SYNOPSIS
.BR rex 
.RI [ options ]
.IR file
.RI [ file ] 
.RI [ ... ]

.SH DESCRIPTION
Remove an old file extension and replace it with another.
Candidate files having the old extension are renamed by removing the old extension and appending the new one.

.PP
This program can be used to remove numeric file extensions added to backup files created by some Motley Tools programs.
Some, but not all, of those programs are listed under the "SEE ALSO" section.
None

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBo\fI extension\fR
The old file extension.
This must match the \fBright-most\fR extension of candidate files for replacement to occur.
Consequently, this \fIextension\fR must start with period and cannot include additional periods.
There is no default extension.

.TP
-\fBn\fI extension\fR
The new file extension.
This is appended to the filename after the old file extension is removed.
Unlike the old file extension, this \fIextension\fR need not start with period and may include multiple periods.
The default is "" which effectively replaces the old extension with nothing.

.TP
.RB - v
Display filenames on stderr as they are renamed.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a file.
This file is renamed only if the \fBright-most\fR extenion matches the argument specified by option \fB-o\fR.
The new filename is then the old filename less the old file extension plus the new file extention.

.SH EXAMPLES
The following example adds an extra extension to files ending in "\fB.txt\fR".
A wildcard is used to select files but only those having the old extension are renamed.
Option \fB-v\fR confirms filename changes.

.PP
   # rex *.* -o ".txt" -n ".txt.save" -v
   rex: alt63d.txt.save <-- alt63d.txt
   rex: alt63x.txt.save <-- alt63x.txt
   rex: temp.txt.save <-- temp.txt

.PP
The next example removes the \fB.002\fR extension from C language header files.
We search for files ending in "\fB.h.002\fR" to avoid renaming other file types that might also have a "\fB.002\fR" extension.
The default new extension is "" but we specified it anyway.

.PP
   # rex *.h.002 -v -o ".002" -n ""
   rex: chars.h <-- chars.h.002
   rex: cmassoc.h <-- cmassoc.h.002
   rex: cmeta.h <-- cmeta.h.002
   rex: error.h <-- error.h.002
   rex: tools.h <-- tools.h.002
   rex: trace.h <-- trace.h.002
   rex: types.h <-- types.h.002
   rex: vtdef.h <-- vtdef.h.002

.SH SEE ALSO
.BR afm ( 1 ),
.BR blank ( 1 ),
.BR cbrief ( 1 ),
.BR cedit ( 1 ),
.BR crlf ( 1 ),
.BR detab ( 1 ),
.BR enfix ( 1 ),
.BR entab ( 1 ),
.BR sbrief ( 1 ),
.BR space ( 1 ),
.BR rex ( 1 ),
.BR trim ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

