.TH search 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
search - print lines matching a regular expression.

.SH SYNOPSIS
.BR search  
.RI [ options ]
.IR file
.RI [ file ]
.RI [ ... ]
.RI [> stdout ]
.PP
.BR search  
.RI [ options ]
.RI [< stdin ]
.RI [> stdout ]

.SH DESCRIPTION
Search files and print lines that match or contain any of several regular expressions.

.SH OPTIONS:
Long options are not supported.
All options are single letters.

.TP
-\fBe\fI expression\fR
A regular expression.
File lines that contain this expression are printed on stdout in a format determined by other program options.
The expression may appear anywhere on the line to qualify as a match.
Essentially, this expression is prefixed by "\fB^.*\fR" and suffixed by "\fB.*$\fR" before use.

.TP
.RB - f
Print the names of files that have lines that match or contain the expression instead of printing the lines.

.TP
.RB - H
Review expression expansion.

.TP
-\fBl\fI expression\fR
A regular expression.
File lines that match this expression are printed on stdout in a format determined by other program options.
The expression must match the entire line to qualify.
Essentially, this expression is prefixed by "\fB^\fR" and suffixed by "\fB$\fR" before use.

.TP
.RB - n
Separate file lines with a file header before and a blank line after.
Prefix printed lines with their line number so that they can be located using a line editor.

.TP
.RB - r
Recursively search folders for named files.
This option may have no effect unless one or more file names specify a relative path or wildcard.
There may also be som interaction between bash and this program.
When in doubt, enclose search names in quotes or apostrophes.

.TP
.RB - R
Display regular expression rules on stdout.
This option takes precedence over previous command line arguments.

.TP
.RB - t 
Traverse filesystem links when searching.

.TP
.RB - T 
Display escape sequence rules on stdout.

.TP 
.RB - v
Invert selection.
Print lines that do not match or contain the expression.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR file
The name of a text file.
The file is not modified.

.SH EXAMPLES
None

.SH SEE ALSO
.BR change ( 7 ),
.BR remove ( 7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
