.TH shakey 7 "GNU General Public License Version 2" "cmassoc-utils-1.8.1" "Motley Toolkit"
.SH NAME
shakey - SHA256 Key Generator
.SH SYNOPSIS
.B shakey
.RI [ options ] 
.IR phrase  
.RI [ phrase ] 
[...]
.SH DESCRIPTION
Convert one or more phrases to encrypted SHA256 keys. Phrases are read as command line arguments, converted keys and printed on stdout. By default, only keys are printed, one key per line, but keys and phrases can both be printed, one pair per line.
.SH OPTIONS
.TP
.RB - e
Enforce length and content rules for phrases. Non-compliant phrases are reported and ignored. Compliant phrases are 12 to 64 7-bit ASCII characters in the range 0x20 (SP) through 0x7F (DEL). Essentially, this includes any character that can be typed on a standard US or UK keyboard, excluding horizontal tab (HT). Be aware that some command shells intercept and act on special characters instead of passing them to the application. In such cases, you may need to include meta characters.
.TP
.RB - q
Enable quiet mode which, for this application, has no effect.
.TP
.RB - v
Enable verbose mode which, for this application, prints the pass phrase after each key.
.TP
.RB - ? ,-- help
Print program help summary on stdout. This option takes precedence over other options on the command line. 
.TP
.RB - ! ,-- version
Print program version information on stdout. This option takes precedence over other options on the command line. 
.SH ARGUMENTS
.TP
.BR phrase
A pass phrase to be converted to key. More than one pass phrase can be entered on the command line. Each phrase will be converted to a key and printed in the order specified. Phrases that contain quotes or special delimiters should be enclosed in quotes or apostrophes. By default, phrases can be any length and contain any ASCII chracter except ASCII NUL. Use option \fB-e\fR to enforce HomePlug AV password character and length rules.
.SH EXAMPLES
The following example prints the SHA256 key for the phrase, "california", entered on the command line. An SHA256 key is 256 bits or 32 bytes expressed as 64 hexadecimal characters. SHA256 is a public domain standard.
.PP
   # shakeys california
   7E8EEA5CC60980270C9CEB75CE8C087D48D726110FD3D17921F774EEFD8E18D8
.PP
The following command prints theSHA256 key for each phrase entered on the command line. Notice that spaces are legal and significant. Phrases containing spaces must be enclosed in quotes.
.PP
   # shakey Supercalifragilisticexpialidocious "The quick brown fox jumped over the lazy dog."
   94730F57D7E41018D963D92FBF11618DCE8274CA2C1BF72274E0285A6013C17B
   68B1282B91DE2C054C36629CB8DD447F12F096D3E3C587978DC2248444633483
.PP
The following command prints both the key and the pass phrase for each pass phrase entered on the command line because the verbose option is specified. Pass phrases startin in column 66 and continue to the end of the line. The keys shown here have been abbreviated due to formatting limitations.
.PP
   # shakey -v "Georgia on my mind" "Pooh Bear"
   1A2A9EA18...F4CAEFA3F2 Georgia on my mind
   7C9849EA9...5DACAD7ACA Pooh Bear
.SH REFERENCES
See standard \fBFIPS180-2 sec 5.3.2\fR for more information on SHA256 encoding.
.SH SEE ALSO
.BR shakeys ( 7 ),
.BR key ( 7 )
.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
