.TH sizeof 1 "August 2013" "cmassoc-tools-1.9.1" "Motley Tools"

.SH NAME
sizeof - host variable information

.SH SYNOPSIS
.BR sizeof  

.SH DESCRIPTION
Print information about host variable types and sizes on stdout.

.SH OPTIONS
None.

.SH ARGUMENTS
None.

.SH EXAMPLES
The following command displays information about host variable types on stdout.

.PP
   # sizeof
   true          is 1
   false         is 0
   order         is 67452301
   
   double        is  8 octets
   long long     is  8 octets
   float         is  4 octets
   long          is  4 octets
   int           is  4 octets
   short         is  2 octets
   char          is  1 octets
   
   (double *)    is  4 octets
   (long long *) is  4 octets
   (float *)     is  4 octets
   (long *)      is  4 octets
   (int *)       is  4 octets
   (short *)     is  4 octets
   (char *)      is  4 octets

.SH SEE ALSO
.BR argv ( 1 ),
.BR argvesc ( 1 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>

