.TH solicit 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
solicit - Qualcomm Atheros Network Solicitor

.SH SYNOPSIS
.BR solicit
.RI [ options ] 

.SH DESCRIPTION
Solicit topology information from powerline network responders.
.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBplc\fR man page for an overview and installation instructions.

.SH OPTIONS

.TP
.RB - i
Select the host Ethernet interface.
All requests are sent via this host interface and only reponses received via this host interface are recognized.
The default interface is \fBeth1\fR because most people use \fBeth0\fR as their principle network connection; however, if environment string "PLC" is defined then it takes precedence over the default interface.
This option then takes precedence over either default.

.TP
.RB - q
Enter quiet mode.
Progress messages are suppressed.

.TP
-\fBw \fImilliseconds\fR
Solicitation frequency in milliseconds.
Values range from 0 through UINT_MAX.
This is the time between solicitation messaged.
The default is forever.

.TP
.RB - v 
Enter verbose mode.
All Etherenet frames sent or received by the program are displayed on stdout.

.TP
-\fB?\fR, --\fBhelp\fR
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
-\fB!\fR, --\fBversion\fR
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH REFERENCES
See the Qualcomm Atheros Simple Network Discovery Protocol for more information about \fBsolicitors\fR, \fBresponders\fR and \fBTLVs\fR.

.SH EXAMPLES
The following example starts a solicitor on interface \fBeth0\fR.
.PP
   # solicit -i eth0

.SH SEE ALSO
.BR plc ( 7 ),
.BR respond ( 7 ),

.SH CREDITS
 Charles Maier <charles.maier@qca.qualcomm.com>
