.TH sweep 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
sweep

.SH SYNOPSIS
.BR sweep 
.IR target-path
.IR source-path
.RI [ source-path ]
.RI [ ... ]
.RB [ options ] 

.SH DESCRIPTION

.SH OPTIONS

.TP
-\fBc\fI s\fR
Print as system command.

.TP
.RB - d
Remove folders.

.TP
.RB - r
Recursive comparison.

.TP
.RB - x
Remove files.

.TP
.RB - q
Quiet mode.

.TP
.RB - v
Verbose mode.

.SH EXAMPLES

.SH SEE ALSO
.BR ff ( 7 ),
.BR purge ( 7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
