.TH symlinks 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
symlinks - symbolic link manager

.SH SYNOPSIS
.BR symlinks
.RI [ options ]
.IR file
.RI [ file ]
.RI [ ... ]

.SH DESCRIPTION
Find and display or remove active or broken symbolic links.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
.RB - a
Select active links.

.TP
.RB - b
Select broken links.

.TP
.RB - c
Print "ln" commands.

.TP
.RB - r
Recursive search.

.TP
.RB - v
Verbose mode.

.TP
.RB - x
Remove selected links.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS
.IR file
The name of the file.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR ff ( 7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
