.TH tls 7 "Mar 2013" "cmassoc-tools-1.8.2" "Motley Tools"

.SH NAME
tls

.SH SYNOPSIS
.BR tls
.RI [ options ]
.IR path
.RI [ path ] 
.RI [ ... ]
.RI [> file ]

.SH DESCRIPTION
.PP
None.

.SH OPTIONS
Long options are not supported.
All options are single letters.

.TP
-\fBn\fI levels\fB
Number of levels displayed.
The default is \fB1\fR.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over previous command line options.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over previous command line options.

.SH ARGUMENTS

.TP
.IR path
The name of a folder file.

.SH EXAMPLES
None.

.SH SEE ALSO
.BR dls ( 7 ),
.BR ff ( 7 )

.SH CREDITS
 Charles Maier <cmaier@cmassoc.net>
